requires 'Mojolicious';
requires 'List::MoreUtils';
requires 'DBI';
requires 'DBD::mysql';
requires 'DBIx::Class';
requires 'DBIx::Class::Migration';
requires 'Sub::Name';
requires 'Digest::SHA1';
requires 'Mojo::mysql';
requires 'Minion';
requires 'DBD::SQLite';
requires 'Minion::Backend::SQLite';
requires 'Mojolicious::Plugin::CORS';
requires 'Mojolicious::Plugin::SecureCORS';
#requires 'Mojolicious::Plugin::JSON::Validator', '>= 0', git => 'git://github.com/FCO/Mojolicious-Plugin-JSON-Validator.git';
#requires 'Mojolicious::Plugin::JSON::Validator', '>= 0', dir => '../Mojolicious-Plugin-JSON-Validator';
#requires 'Mojolicious::Plugin::CommandWS', '>= 0', git => 'git://github.com/FCO/Mojolicious-Plugin-CommandWS.git';
#requires 'Mojolicious::Plugin::CommandWS', '>= 0', dir => '../Mojolicious-Plugin-CommandWS';
requires 'HTML::TokeParser';
requires 'DateTime';
requires 'Moose';
requires 'Params::Validate';
requires 'JSON';
requires 'JSON::XS';
requires 'Data::Dump::Streamer';
requires 'JSON::Validator';
