db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=test
tws:
  build: .
  ports:
    - "3000:3000"
  links:
    - db
  #command: carton exec dbic-migration -S 'TWS::Schema' -Ilib install --dsn="dbi:mysql:database=tws;host=db;port=3306;password=test" --database MySQL
