version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=tws
    restart: always
  tws:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minion
    restart: always
  minion:
    build: .
    depends_on:
      - db
    restart: always
    command: carton exec perl -IMojolicious-Plugin-CommandWS/lib script/tws minion worker
  webapp:
    image: webapp
    ports:
      - "80:80"
    depends_on:
      - tws
    restart: always
